image: reactnativecommunity/react-native-android

stages:
  - build

build:
  stage: build
  script:
    - yarn install
    - cd android && chmod +x gradlew
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - android/app/build/outputs/
