image: reactnativecommunity/react-native-android

stages:
  - build

build:
  stage: build
  script:
    - yarn install
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/
